import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "./store";

export interface UserState {}

const initialState: UserState = {};

// The slice contains all of our state information, reducers, actions, etc for the user
export const userSlice = createSlice({
  name: "user",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
});

// We export the actions generated by our slice based on our reducers
export const {} = userSlice.actions;

export default userSlice.reducer;
